<a href="https://colab.research.google.com/github/illusoryTwin/FoR/blob/main/assig3/for_assig3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Define the fundamental functions

### Transformation matrices

In [12]:
import numpy as np

# Define rotation and translation functions
def rotate_z(theta):
    return np.array([[np.cos(theta), -np.sin(theta), 0, 0],
                     [np.sin(theta), np.cos(theta), 0, 0],
                     [0, 0, 1, 0],
                     [0, 0, 0, 1]])

def rotate_x(theta):
    return np.array([[1, 0, 0, 0],
                     [0, np.cos(theta), -np.sin(theta), 0],
                     [0, np.sin(theta), np.cos(theta), 0],
                     [0, 0, 0, 1]])

def rotate_y(theta):
    return np.array([[np.cos(theta), 0, np.sin(theta), 0],
                     [0, 1, 0, 0],
                     [-np.sin(theta), 0, np.cos(theta), 0],
                     [0, 0, 0, 1]])

def translate_x(d):
    return np.array([[1, 0, 0, d],
                     [0, 1, 0, 0],
                     [0, 0, 1, 0],
                     [0, 0, 0, 1]])

def translate_y(d):
    return np.array([[1, 0, 0, 0],
                     [0, 1, 0, d],
                     [0, 0, 1, 0],
                     [0, 0, 0, 1]])

def translate_z(d):
    return np.array([[1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 1, d],
                     [0, 0, 0, 1]])


def validate_matrices(matrices):
  tolerance = 1e-12

  # Define a function to check if a value is close to zero within the tolerance
  def is_close_to_zero(value):
      return abs(value) < tolerance

  validated_matrices = []

  for matrix in matrices:
    for i in range(matrix.shape[0]):
      for j in range(matrix.shape[1]):
        if is_close_to_zero(matrix[i][j]):
          matrix[i][j] = 0
    validated_matrices.append(matrix)

  return validated_matrices



### Symbolic transformation matrices

In [5]:
import sympy as sp

# Define symbolic rotation and translation functions
def rotate_z_sym(theta):
    return sp.Matrix([
        [sp.cos(theta), -sp.sin(theta), 0, 0],
        [sp.sin(theta), sp.cos(theta), 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

def rotate_x_sym(theta):
    return sp.Matrix([
        [1, 0, 0, 0],
        [0, sp.cos(theta), -sp.sin(theta), 0],
        [0, sp.sin(theta), sp.cos(theta), 0],
        [0, 0, 0, 1]
    ])

def rotate_y_sym(theta):
    return sp.Matrix([
        [sp.cos(theta), 0, sp.sin(theta), 0],
        [0, 1, 0, 0],
        [-sp.sin(theta), 0, sp.cos(theta), 0],
        [0, 0, 0, 1]
    ])

def translate_x_sym(d):
    return sp.Matrix([
        [1, 0, 0, d],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

def translate_y_sym(d):
    return sp.Matrix([
        [1, 0, 0, 0],
        [0, 1, 0, d],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

def translate_z_sym(d):
    return sp.Matrix([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, d],
        [0, 0, 0, 1]
    ])

def validate_matrix_sym(matrix):
    tolerance = 1e-12
    # Define a function to check if a value is close to zero within the tolerance
    def is_close_to_zero(value):
        return abs(value) < tolerance

    # Iterate through each element in the matrix
    for i in range(matrix.rows):
        for j in range(matrix.cols):
            # If the element is close to zero, set it to zero
            if is_close_to_zero(matrix[i, j]):
                matrix[i, j] = 0


# Solving dynamics
### Define the Manipulator class

In [2]:
import numpy as np

class Manipulator:
    def __init__(self, l, m=[1 for _ in range(6)], r=[0.05 for _ in range(6)],\
                 q=None, q_prev=None):
        self.l = l  # length of the links
        self.m = m  # mass of the links
        self.q = q  # configuration parameters (angles)
        self.q_prev = q_prev # the previous configuration state
        self.r = r  # radii of cylindrical links
        self.h = l  # heights of cylindrical links
        self.lc = [l_i / 2 for l_i in l]  # distances to the links' CoMs

    def set_config(self, q):
        self.q = q

    def get_config(self):
        return self.q

    def get_config_in_pi(self, q):
        return [str(q_ / np.pi) + "pi" for q_ in q]

    def set_prev_config(self, q_prev):
        self.q_prev = q_prev

    def get_prev_config(self):
        return self.get_config_in_pi(self.q_prev)

    def get_delta_q_in_pi(self):
        delta_q = [q_ - q_prev_ for (q_, q_prev_) in zip(self.q, self.q_prev)]
        return self.get_config_in_pi(delta_q)  # Added 'self' parameter

    def get_delta_q(self):
        delta_q = [q_ - q_prev_ for (q_, q_prev_) in zip(self.q, self.q_prev)]
        return delta_q  # Added 'self' parameter


# Example of usage
l = [1 for _ in range(6)]
m = [1 for _ in range(6)]
q = [np.pi/2, np.pi/3, np.pi/4, 0, np.pi/12, 0]
q_prev = [np.pi/2, np.pi/6, np.pi/4, np.pi/12, np.pi/12, 0]

manipulator = Manipulator(l, m)
manipulator.set_config(q)
manipulator.set_prev_config(q_prev)

print(manipulator.get_config())
print(manipulator.get_prev_config())
print("delta q: ", manipulator.get_delta_q_in_pi())

[1.5707963267948966, 1.0471975511965976, 0.7853981633974483, 0, 0.2617993877991494, 0]
['0.5pi', '0.16666666666666666pi', '0.25pi', '0.08333333333333333pi', '0.08333333333333333pi', '0.0pi']
delta q:  ['0.0pi', '0.16666666666666666pi', '0.0pi', '-0.08333333333333333pi', '0.0pi', '0.0pi']


### Find center of mass

In [19]:
def calculate_com(Manipiulator: manipulator):
    theta1, theta2, theta3, theta4, theta5, theta6 = manipulator.get_config()
    lc1, lc2, lc3, lc4, lc5, lc6 = manipulator.lc
    l1, l2, l3, l4, l5, l6 = manipulator.l

    T_0 = np.identity(4)
    T_01 = rotate_z(theta1) @ translate_z(l1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)
    T_12 = rotate_z(theta2) @ translate_x(l2)
    T_23 = rotate_z(theta3) @ translate_x(l3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)
    T_34 = rotate_z(theta4) @ translate_z(l4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)
    T_45 = rotate_z(theta5) @ translate_y(l5) @ rotate_x(-np.pi/2)
    T_56 = rotate_z(theta6) @ translate_z(l6)


    com1 = T_0 @ rotate_z(theta1) @ translate_z(lc1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)

    T_01 = T_0 @ T_01
    com2 = T_01 @ rotate_z(theta2) @ translate_x(lc2)

    T_02 = T_01 @ T_12
    com3 = T_02 @ rotate_z(theta3) @ translate_x(lc3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)

    T_03 = T_02 @ T_23
    com4 = T_03 @ rotate_z(theta4) @ translate_z(lc4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)

    T_04 = T_03 @ T_34
    com5 = T_04 @ rotate_z(theta5) @ translate_y(lc5) @ rotate_x(-np.pi/2)

    T_05 = T_04 @ T_45
    com6 = T_05 @ rotate_z(theta6) @ translate_z(lc6)

    coms = [com1, com2, com3, com4, com5, com6]
    coms = validate_matrices(coms)
    return coms

q = [0]*6
l = [1 for _ in range(6)]
m = [1 for _ in range(6)]

manipulator = Manipulator(l, m)
manipulator.set_config(q)
coms_matrices = calculate_com(manipulator)
coms_matrices

com1 [[ 6.12323400e-17 -6.12323400e-17  1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  3.74939946e-33 -6.12323400e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  5.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
com2 [[ 6.12323400e-17 -6.12323400e-17  1.00000000e+00  3.06161700e-17]
 [ 1.00000000e+00  3.74939946e-33 -6.12323400e-17  5.00000000e-01]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
com3 [[-1.22464680e-16  1.00000000e+00  1.22464680e-16  9.18485099e-17]
 [ 1.12481984e-32 -1.22464680e-16  1.00000000e+00  1.50000000e+00]
 [ 1.00000000e+00  1.22464680e-16  3.74939946e-33  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
com4 [[ 1.2246468e-16  6.1232340e-17  1.0000000e+00  1.8369702e-16]
 [ 1.2246468e-16  1.0000000e+00 -6.1232340e-17  2.5000000e+00]
 [-1.0000000e+00  1.2246468e-16  1.2246468e-16 

[array([[0. , 0. , 1. , 0. ],
        [1. , 0. , 0. , 0. ],
        [0. , 1. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]]),
 array([[0. , 0. , 1. , 0. ],
        [1. , 0. , 0. , 0.5],
        [0. , 1. , 0. , 1. ],
        [0. , 0. , 0. , 1. ]]),
 array([[0. , 1. , 0. , 0. ],
        [0. , 0. , 1. , 1.5],
        [1. , 0. , 0. , 1. ],
        [0. , 0. , 0. , 1. ]]),
 array([[ 0. ,  0. ,  1. ,  0. ],
        [ 0. ,  1. ,  0. ,  2.5],
        [-1. ,  0. ,  0. ,  1. ],
        [ 0. ,  0. ,  0. ,  1. ]]),
 array([[ 0. , -1. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  3.5],
        [-1. ,  0. ,  0. ,  1. ],
        [ 0. ,  0. ,  0. ,  1. ]]),
 array([[ 0. , -1. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  4.5],
        [-1. ,  0. ,  0. ,  1. ],
        [ 0. ,  0. ,  0. ,  1. ]])]

In [ ]:
from sympy import symbols

def calculate_com_symb(manipulator: Manipulator):
    theta1, theta2, theta3, theta4, theta5, theta6 = symbols('theta1 theta2 theta3 theta4 theta5 theta6')
    l = manipulator.l
    lc = manipulator.lc

    T_01 = rotate_z_sym(theta1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)
    com1 = T_01 @ translate_z(lc[0])

    T_02 = T_01 @ translate_z(l[0]) @ rotate_z_sym(theta2)
    com2 = T_02 @ translate_x(lc[1])

    T_03 = T_02 @ translate_x(l[1]) @ rotate_z_sym(theta3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)
    com3 = T_03 @ translate_x(lc[2])

    T_04 = T_03 @ translate_x(l[2]) @ rotate_z_sym(theta4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)
    com4 = T_04 @ translate_z(lc[3])

    T_05 = T_04 @ translate_z(l[3]) @ rotate_z_sym(theta5) @ rotate_x(-np.pi/2)
    com5 = T_05 @ translate_y(lc[4])

    T_06 = T_05 @ translate_y(l[4]) @ rotate_z_sym(theta6)
    com6 = T_06 @ translate_z(lc[5])
    coms = [com1, com2, com3, com4, com5, com6]

    return coms

coms_matrices_symb = calculate_com_symb(manipulator)
coms_matrices_symb

### Calculate inertia/mass matrices assuming that the manipulator's links are cylindrical

In [7]:
class InertiaMatrixForCylinder:
    def __init__(self, m, r, h):
        self.m = m
        self.r = r
        self.h = h

    def get_inertia_matrix(self):
        I = np.array([[self.m*self.h**2/2 + self.m*self.r**2/4, 0, 0],
                      [0, self.m*self.h**2/12 + self.m*self.r**2/4, 0],
                      [0, 0, self.m*self.r**2/2]])
        return I

In [ ]:
# Example of usage

l = [1 for _ in range(6)]
m = [1 for _ in range(6)]
# q = [np.pi/2, np.pi/3, np.pi/4, 0, np.pi/12, 0]

manipulator = Manipulator(l, m)
# manipulator.set_config(q)

inertia_matrices = []


for i in range(6):
  inertia_matrix = InertiaMatrixForCylinder(manipulator.m[i], manipulator.r[i], manipulator.h[i])
  inertia_matrices.append(inertia_matrix.get_inertia_matrix())

inertia_matrices

[array([[0.500625  , 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.00125   ]]),
 array([[0.500625  , 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.00125   ]]),
 array([[0.500625  , 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.00125   ]]),
 array([[0.500625  , 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.00125   ]]),
 array([[0.500625  , 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.00125   ]]),
 array([[0.500625  , 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.00125   ]])]

In [ ]:
# CHECK

# q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6')
# q_symb = [q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb]

# print(sp.diff(coms_matrices_symb[0][:3, 3], q_symb[0]))
# coms_matrices_symb[0][:3, 3]

Matrix([[-0.5*sin(theta1) + 3.06161699786838e-17*cos(theta1)], [3.06161699786838e-17*sin(theta1) + 0.5*cos(theta1)], [0]])


Matrix([
[3.06161699786838e-17*sin(theta1) + 0.5*cos(theta1)],
[0.5*sin(theta1) - 3.06161699786838e-17*cos(theta1)],
[                              3.06161699786838e-17]])

### Calculate the Jacobian J_v

In [ ]:
q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6')
q_symb = [q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb]


def calculate_jacobian_v(com_symb):
    jacobian_v = []

    for k in range(6):
        row = []
        for i in range(3):
            col = []
            for j in range(6):
                col.append(sp.diff(com_symb[k][i, 3], q_symb[j]))
            row.append(col)
        jacobian_v.append(row)

    return sp.Array(jacobian_v)


def calc_num_jacobian_v(com_symb, q_num):
    jac_v_symb = calculate_jacobian_v(com_symb)
    jac_v_num = jac_v_symb.subs({q1_symb: q_num[0], q2_symb: q_num[1], q3_symb: q_num[2], q4_symb: q_num[3], q5_symb: q_num[4], q6_symb: q_num[5]})
    return sp.Array(jac_v_num)

# Example of usage
q_vals = manipulator.get_delta_q()
jac_v = calc_num_jacobian_v(coms_matrices_symb, q_vals)
jac_v

[[[3.06161699786838e-17, 0, 0, 0, 0, 0], [0.5, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], [[-0.433012701892219, -4.18224659574646e-17, 0, 0, 0, 0], [1.0, -0.25, 0, 0, 0, 0], [0, 0.433012701892219, 0, 0, 0, 0]], [[-0.616025403784439, -9.48512278937099e-17, -1.12062959787808e-17, 0, 0, 0], [1.0, -0.933012701892219, -0.433012701892219, 0, 0, 0], [0, 0.616025403784439, -0.25, 0, 0, 0]], [[-0.301320642508808, -1.08957926696855e-16, -2.53129947819258e-17, 0.12940952255126, 0, 0], [1.48296291314453, -1.47809733780545, -0.978097337805445, 0.241481456572267, 0, 0], [0, 0.301320642508809, -0.56470476127563, -0.418258151868904, 0, 0]], [[-0.301320642508808, -1.08957926696855e-16, -2.53129947819258e-17, 0.12940952255126, -7.92404787857942e-18, 0], [1.48296291314453, -1.47809733780545, -0.978097337805445, 0.241481456572267, -1.47864746422334e-17, 0], [0, 0.301320642508809, -0.56470476127563, -0.418258151868904, 2.5610925345177e-17, 0]], [[-0.799038105676658, -1.47879989829955e-16, -6.42350579150261e-17, 

### Calculate the Jacobian J_w

In [ ]:
def calculate_jacobian_w(coms):
    jacobian_w = np.zeros((6, 3, 6))
    u = [np.array([0, 0, 1]),  coms[0][:3, 2],  coms[1][:3, 2], coms[2][:3, 2],  coms[3][:3, 2],  coms[4][:3, 2]]
    for i in range(6):
      for j in range(i+1):
        jacobian_w[i][:, j] = u[j]
    return jacobian_w

coms_matrices = calculate_com(manipulator)
jac_w = calculate_jacobian_w(coms_matrices)
jac_w

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]],

       [[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ,
         0.        ],
        [1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]],

       [[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 1.        , 1.        , 0.        , 0.        ,
         0.        ],
        [1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]],

       [[0.        , 0.        , 0.        , 0.25881905, 0.        ,
         0.        ],
        [0.        , 1.        , 1.        , 0.        , 0.        ,
         0.    

### Define the rotation matrix

In [ ]:
def define_R(com):
    R = np.zeros((6, 3, 3))
    com = np.array(com)
    for k in range(6):
        R[k] = com[k, :3, :3]
    return R

coms_matrices = calculate_com(manipulator)

R = define_R(coms_matrices)
R

array([[[-1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ],
        [ 0.        ,  1.        ,  0.        ]],

       [[-0.5       ,  0.8660254 ,  0.        ],
        [ 0.        ,  0.        ,  1.        ],
        [ 0.8660254 ,  0.5       ,  0.        ]],

       [[ 0.96592583,  0.        ,  0.25881905],
        [ 0.        ,  1.        ,  0.        ],
        [-0.25881905,  0.        ,  0.96592583]],

       [[-0.96592583,  0.25881905,  0.        ],
        [ 0.        ,  0.        ,  1.        ],
        [ 0.25881905,  0.96592583,  0.        ]],

       [[-0.8660254 ,  0.        ,  0.5       ],
        [ 0.        , -1.        ,  0.        ],
        [ 0.5       ,  0.        ,  0.8660254 ]],

       [[-0.8660254 ,  0.        ,  0.5       ],
        [ 0.        , -1.        ,  0.        ],
        [ 0.5       ,  0.        ,  0.8660254 ]]])

In [ ]:
jac_w = calculate_jacobian_w(coms_matrices)[0]
print(jac_w.shape)
jac_w_T = np.transpose(jac_w)
print("jac_w_T", jac_w_T)
print("R[0]", R[0])
print(jac_w_T @ R[0])

(3, 6)
jac_w_T [[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
R[0] [[-1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
from sys import flags
class MassMatrix:

    def __init__(self, manipulator):
        self.manipulator = manipulator
        self.com = calculate_com(self.manipulator)
        self.com_symb = calculate_com_symb(manipulator)

        if manipulator.q_prev is not None and manipulator.q is not None:
          self.delta_q = manipulator.get_delta_q()
          self.numeric = True
          print("NB: Calculations are numeric.\n")

        else:
          self.numeric = False
          print("NB: Calculations are symbolic!\n")

    def compute(self):
      M = np.zeros((6, 6))
      for i in range(6):
        m_i = manipulator.m[i]
        inertia_matrx = InertiaMatrixForCylinder(m_i, manipulator.r[i],\
                                                 manipulator.h[i])
        I_i = inertia_matrix.get_inertia_matrix()
        R_i = define_R(self.com)[i]

        if self.numeric is False:
          Jv_i = calculate_jacobian_v(self.com_symb)[i]
        else:
          Jv_i = calc_num_jacobian_v(self.com_symb, self.delta_q)[i]

        Jw_i = calculate_jacobian_w(self.com)[i]
        # Jw_i = np.array([Jw_i])
        ang = np.array([np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i])
        M += ang
        print("ang", ang)
        print("Jw_i^T @ R_i @ I_i @ R_i^T @ Jw_i", np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i)
        # M[i] += np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i
        # print(np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i).shape
        # @ I_i @ np.transpose(R_i) @ Jw_i

        #  (m_i * np.transpose(Jv_i) @ Jv_i) # + np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i)

      return M

mass_matrix = MassMatrix(manipulator)
mass_matrix.compute()


NB: Calculations are numeric.



ValueError: non-broadcastable output operand with shape (6,6) doesn't match the broadcast shape (1,6,6)

In [ ]:
calculate_com(manipulator)

TypeError: ufunc 'cos' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

# Coriolis matrix

In [ ]:
class CoriolisMatix:
  def __init__():
    pass

  def compute():
    coriolis_matrix =  np.zeros(6, 6)
    for i in range(6):
      for j in range(6):
        for k in range(6):
          coriolis_matrix[i, j] += 1/2 * (sp.diff(M[i, j], q_symb[k]) + sp.diff() - sp.diff())

           diff(Mq[i, j], q_symb[k]) + diff(Mq[i, k], q_symb[k]) - diff(Mq[j, k], q_symb[i])) * q_dot[
                                k]
