<a href="https://colab.research.google.com/github/illusoryTwin/FoR/blob/main/assig3/for_assig3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Define the fundamental functions

### Transformation matrices

In [29]:
import numpy as np

# Define rotation and translation functions
def rotate_z(theta):
    return np.array([[np.cos(theta), -np.sin(theta), 0, 0],
                     [np.sin(theta), np.cos(theta), 0, 0],
                     [0, 0, 1, 0],
                     [0, 0, 0, 1]])

def rotate_x(theta):
    return np.array([[1, 0, 0, 0],
                     [0, np.cos(theta), -np.sin(theta), 0],
                     [0, np.sin(theta), np.cos(theta), 0],
                     [0, 0, 0, 1]])

def rotate_y(theta):
    return np.array([[np.cos(theta), 0, np.sin(theta), 0],
                     [0, 1, 0, 0],
                     [-np.sin(theta), 0, np.cos(theta), 0],
                     [0, 0, 0, 1]])

def translate_x(d):
    return np.array([[1, 0, 0, d],
                     [0, 1, 0, 0],
                     [0, 0, 1, 0],
                     [0, 0, 0, 1]])

def translate_y(d):
    return np.array([[1, 0, 0, 0],
                     [0, 1, 0, d],
                     [0, 0, 1, 0],
                     [0, 0, 0, 1]])

def translate_z(d):
    return np.array([[1, 0, 0, 0],
                     [0, 1, 0, 0],
                     [0, 0, 1, d],
                     [0, 0, 0, 1]])


def validate_matrices(matrices):
  tolerance = 1e-12

  # Define a function to check if a value is close to zero within the tolerance
  def is_close_to_zero(value):
      return abs(value) < tolerance

  validated_matrices = []

  for matrix in matrices:
    for i in range(matrix.shape[0]):
      for j in range(matrix.shape[1]):
        if is_close_to_zero(matrix[i][j]):
          matrix[i][j] = 0
    validated_matrices.append(matrix)

  return validated_matrices



### Symbolic transformation matrices

In [30]:
import sympy as sp

# Define symbolic rotation and translation functions
def rotate_z_sym(theta):
    return sp.Matrix([
        [sp.cos(theta), -sp.sin(theta), 0, 0],
        [sp.sin(theta), sp.cos(theta), 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

def rotate_x_sym(theta):
    return sp.Matrix([
        [1, 0, 0, 0],
        [0, sp.cos(theta), -sp.sin(theta), 0],
        [0, sp.sin(theta), sp.cos(theta), 0],
        [0, 0, 0, 1]
    ])

def rotate_y_sym(theta):
    return sp.Matrix([
        [sp.cos(theta), 0, sp.sin(theta), 0],
        [0, 1, 0, 0],
        [-sp.sin(theta), 0, sp.cos(theta), 0],
        [0, 0, 0, 1]
    ])

def translate_x_sym(d):
    return sp.Matrix([
        [1, 0, 0, d],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

def translate_y_sym(d):
    return sp.Matrix([
        [1, 0, 0, 0],
        [0, 1, 0, d],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

def translate_z_sym(d):
    return sp.Matrix([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, d],
        [0, 0, 0, 1]
    ])

def validate_matrix_sym(matrix):
    tolerance = 1e-12
    # Define a function to check if a value is close to zero within the tolerance
    def is_close_to_zero(value):
        return abs(value) < tolerance

    # Iterate through each element in the matrix
    for i in range(matrix.rows):
        for j in range(matrix.cols):
            # If the element is close to zero, set it to zero
            if is_close_to_zero(matrix[i, j]):
                matrix[i, j] = 0


# Solving dynamics
### Define the Manipulator class

In [57]:
import numpy as np

# class Manipulator:
#     def __init__(self, l, m=[1 for _ in range(6)], r=[0.05 for _ in range(6)],\
#                  q=None, q_prev=None):
#         self.l = l  # length of the links
#         self.m = m  # mass of the links
#         self.q = q  # configuration parameters (angles)
#         self.q_prev = q_prev # the previous configuration state
#         self.r = r  # radii of cylindrical links
#         self.h = l  # heights of cylindrical links
#         self.lc = [l_i / 2 for l_i in l]  # distances to the links' CoMs

#     def set_config(self, q):
#         self.q = q

#     def get_config(self):
#         return self.q

#     def get_config_in_pi(self, q):
#         return [str(q_ / np.pi) + "pi" for q_ in q]

#     def set_prev_config(self, q_prev):
#         self.q_prev = q_prev

#     def get_prev_config(self):
#         return self.get_config_in_pi(self.q_prev)

#     def get_delta_q_in_pi(self):
#         delta_q = [q_ - q_prev_ for (q_, q_prev_) in zip(self.q, self.q_prev)]
#         return self.get_config_in_pi(delta_q)  # Added 'self' parameter

#     def get_delta_q(self):
#         if self.q is None or self.prev_q is None:
#             # return "Error! Set a proper configuration"
#             raise ValueError("Error! Set a proper configuration")
#         else:
#             delta_q = [q_ - q_prev_ for (q_, q_prev_) in zip(self.q, self.prev_q)]
#             return delta_q


# class Manipulator:
#     def __init__(self, l, m=None):
#         self.l = l
#         self.m = m
#         self.q = None
#         self.prev_q = None  # Initialize prev_q attribute

#     def set_config(self, q_):
#         if self.q is None:
#             self.q = q_ if isinstance(q_, list) else [q_]
#         else:
#             self.prev_q = self.q  # Update prev_q with current q before updating q
#             self.q.extend(q_ if isinstance(q_, list) else [q_])

#     def get_config(self):
#         return self.q

#     def get_config_in_pi(self):
#         return [str(q_ / np.pi) + "pi" for q_ in self.q]

#     def get_delta_q(self):
#         if self.q is None or self.prev_q is None:
#             raise ValueError("Error! Set a proper configuration")
#         else:
#             delta_q = [q_ - q_prev_ for (q_, q_prev_) in zip(self.q, self.prev_q)]
#             return delta_q

class Manipulator:
    def __init__(self, l, m=[1 for _ in range(6)], r=[0.05 for _ in range(6)]):
        self.l = l # length of the links
        self.m = m # mass of the links
        self.q = None # configuration parameters (angles)
        self.prev_q = None # the previous configuration state
        self.r = r # radii of cylindrical links
        self.h = l  # heights of cylindrical links
        self.lc = [l_i / 2 for l_i in l]  # distances to the links' CoMs


#     def __init__(self, l, m=[1 for _ in range(6)], r=[0.05 for _ in range(6)],\
#                  q=None, q_prev=None):
#         self.l = l  # length of the links
#         self.m = m  # mass of the links
#         self.q = q  # configuration parameters (angles)
#         self.q_prev = q_prev # the previous configuration state
#         self.r = r  # radii of cylindrical links
#         self.h = l  # heights of cylindrical links
#         self.lc = [l_i / 2 for l_i in l]  # distances to the links' CoMs

    def set_config(self, q_):
        if self.q is None:
            self.q = q_ if isinstance(q_, list) else [q_]
        else:
            self.prev_q = self.q
            self.q.extend(q_ if isinstance(q_, list) else [q_])

    def get_config(self):
        return self.q

    def get_config_in_pi(self):
        return [str(q_ / np.pi) + "pi" for q_ in self.q]

    def set_prev_config(self, prev_q_):
        if self.prev_q is None:
            self.prev_q = prev_q_ if isinstance(prev_q_, list) else [prev_q_]
        else:
            raise ValueError("Previous configuration is already set. Cannot set again.")

    def get_prev_config(self):
        if self.prev_q is None:
            raise ValueError("Previous configuration is not set.")
        else:
            return self.prev_q

    def get_delta_q(self):
        if self.q is None or self.prev_q is None:
            raise ValueError("Error! Set a proper configuration")
        else:
            delta_q = [q_ - q_prev_ for (q_, q_prev_) in zip(self.q, self.prev_q)]
            return delta_q

    def get_delta_q_in_pi(self):
        if self.q is None or self.prev_q is None:
            raise ValueError("Error! Set a proper configuration")
        else:
            delta_q_pi = [(q_ - q_prev_) / np.pi for (q_, q_prev_) in zip(self.q, self.prev_q)]
            return delta_q_pi

    def get_prev_config_in_pi(self):
        if self.prev_q is None:
            raise ValueError("Previous configuration is not set.")
        else:
            return [q_prev_ / np.pi for q_prev_ in self.prev_q]



# Example of usage
l = [1 for _ in range(6)]
m = [1 for _ in range(6)]
q = [np.pi/2, np.pi/3, np.pi/4, 0, np.pi/12, 0]
q_prev = [np.pi/2, np.pi/6, np.pi/4, np.pi/12, np.pi/12, 0]

manipulator = Manipulator(l, m)
manipulator.set_config(q)
manipulator.set_prev_config(q_prev)

print(manipulator.get_config())
print(manipulator.get_prev_config())
print("delta q: ", manipulator.get_delta_q_in_pi())

[1.5707963267948966, 1.0471975511965976, 0.7853981633974483, 0, 0.2617993877991494, 0]
[1.5707963267948966, 0.5235987755982988, 0.7853981633974483, 0.2617993877991494, 0.2617993877991494, 0]
delta q:  [0.0, 0.16666666666666666, 0.0, -0.08333333333333333, 0.0, 0.0]


### Find center of mass

In [58]:
def calculate_com(manipulator: Manipulator):
    theta1, theta2, theta3, theta4, theta5, theta6 = manipulator.get_config()
    lc1, lc2, lc3, lc4, lc5, lc6 = manipulator.lc
    l1, l2, l3, l4, l5, l6 = manipulator.l

    T_0 = np.identity(4)
    T_01 = rotate_z(theta1) @ translate_z(l1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)
    T_12 = rotate_z(theta2) @ translate_x(l2)
    T_23 = rotate_z(theta3) @ translate_x(l3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)
    T_34 = rotate_z(theta4) @ translate_z(l4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)
    T_45 = rotate_z(theta5) @ translate_y(l5) @ rotate_x(-np.pi/2)
    T_56 = rotate_z(theta6) @ translate_z(l6)


    com1 = T_0 @ rotate_z(theta1) @ translate_z(lc1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)

    T_01 = T_0 @ T_01
    com2 = T_01 @ rotate_z(theta2) @ translate_x(lc2)

    T_02 = T_01 @ T_12
    com3 = T_02 @ rotate_z(theta3) @ translate_x(lc3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)

    T_03 = T_02 @ T_23
    com4 = T_03 @ rotate_z(theta4) @ translate_z(lc4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)

    T_04 = T_03 @ T_34
    com5 = T_04 @ rotate_z(theta5) @ translate_y(lc5) @ rotate_x(-np.pi/2)

    T_05 = T_04 @ T_45
    com6 = T_05 @ rotate_z(theta6) @ translate_z(lc6)

    coms = [com1, com2, com3, com4, com5, com6]
    coms = validate_matrices(coms)
    return coms

q = [0]*6
l = [1 for _ in range(6)]
m = [1 for _ in range(6)]

manipulator = Manipulator(l, m)
manipulator.set_config(q)
coms_matrices = calculate_com(manipulator)
coms_matrices

[array([[0. , 0. , 1. , 0. ],
        [1. , 0. , 0. , 0. ],
        [0. , 1. , 0. , 0.5],
        [0. , 0. , 0. , 1. ]]),
 array([[0. , 0. , 1. , 0. ],
        [1. , 0. , 0. , 0.5],
        [0. , 1. , 0. , 1. ],
        [0. , 0. , 0. , 1. ]]),
 array([[0. , 1. , 0. , 0. ],
        [0. , 0. , 1. , 1.5],
        [1. , 0. , 0. , 1. ],
        [0. , 0. , 0. , 1. ]]),
 array([[ 0. ,  0. ,  1. ,  0. ],
        [ 0. ,  1. ,  0. ,  2.5],
        [-1. ,  0. ,  0. ,  1. ],
        [ 0. ,  0. ,  0. ,  1. ]]),
 array([[ 0. , -1. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  3.5],
        [-1. ,  0. ,  0. ,  1. ],
        [ 0. ,  0. ,  0. ,  1. ]]),
 array([[ 0. , -1. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  4.5],
        [-1. ,  0. ,  0. ,  1. ],
        [ 0. ,  0. ,  0. ,  1. ]])]

In [59]:
from sympy import symbols

# def calculate_com_symb(manipulator: Manipulator):
#     theta1, theta2, theta3, theta4, theta5, theta6 = symbols('theta1 theta2 theta3 theta4 theta5 theta6')
#     l = manipulator.l
#     lc = manipulator.lc

#     T_01 = rotate_z_sym(theta1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)
#     com1 = T_01 @ translate_z(lc[0])

#     T_02 = T_01 @ translate_z(l[0]) @ rotate_z_sym(theta2)
#     com2 = T_02 @ translate_x(lc[1])

#     T_03 = T_02 @ translate_x(l[1]) @ rotate_z_sym(theta3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)
#     com3 = T_03 @ translate_x(lc[2])

#     T_04 = T_03 @ translate_x(l[2]) @ rotate_z_sym(theta4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)
#     com4 = T_04 @ translate_z(lc[3])

#     T_05 = T_04 @ translate_z(l[3]) @ rotate_z_sym(theta5) @ rotate_x(-np.pi/2)
#     com5 = T_05 @ translate_y(lc[4])

#     T_06 = T_05 @ translate_y(l[4]) @ rotate_z_sym(theta6)
#     com6 = T_06 @ translate_z(lc[5])
#     coms = [com1, com2, com3, com4, com5, com6]

#     return coms

def calculate_com_symb(manipulator: Manipulator):
    theta1, theta2, theta3, theta4, theta5, theta6 = symbols('theta1 theta2 theta3 theta4 theta5 theta6')
    lc1, lc2, lc3, lc4, lc5, lc6 = manipulator.lc
    l1, l2, l3, l4, l5, l6 = manipulator.l

    T_0 = np.identity(4)
    T_01 = rotate_z_sym(theta1) @ translate_z(l1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)
    T_12 = rotate_z_sym(theta2) @ translate_x(l2)
    T_23 = rotate_z_sym(theta3) @ translate_x(l3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)
    T_34 = rotate_z_sym(theta4) @ translate_z(l4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)
    T_45 = rotate_z_sym(theta5) @ translate_y(l5) @ rotate_x(-np.pi/2)
    T_56 = rotate_z_sym(theta6) @ translate_z(l6)


    com1 = T_0 @ rotate_z_sym(theta1) @ translate_z(lc1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)

    T_01 = T_0 @ T_01
    com2 = T_01 @ rotate_z_sym(theta2) @ translate_x(lc2)

    T_02 = T_01 @ T_12
    com3 = T_02 @ rotate_z_sym(theta3) @ translate_x(lc3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)

    T_03 = T_02 @ T_23
    com4 = T_03 @ rotate_z_sym(theta4) @ translate_z(lc4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)

    T_04 = T_03 @ T_34
    com5 = T_04 @ rotate_z_sym(theta5) @ translate_y(lc5) @ rotate_x(-np.pi/2)

    T_05 = T_04 @ T_45
    com6 = T_05 @ rotate_z_sym(theta6) @ translate_z(lc6)

    coms = [com1, com2, com3, com4, com5, com6]
    return coms


coms_matrices_symb = calculate_com_symb(manipulator)
# coms_matrices_symb

### Calculate inertia/mass matrices assuming that the manipulator's links are cylindrical

In [60]:
class InertiaMatrixForCylinder:
    def __init__(self, m, r, h):
        self.m = m
        self.r = r
        self.h = h

    def get_inertia_matrix(self):
        I = np.array([[self.m*self.h**2/12 + self.m*self.r**2/4, 0, 0],
                      [0, self.m*self.h**2/12 + self.m*self.r**2/4, 0],
                      [0, 0, self.m*self.r**2/4]])
        return I

In [61]:
# Example of usage

l = [1 for _ in range(6)]
m = [1 for _ in range(6)]
# q = [np.pi/2, np.pi/3, np.pi/4, 0, np.pi/12, 0]

manipulator = Manipulator(l, m)
# manipulator.set_config(q)

inertia_matrices = []


for i in range(6):
  inertia_matrix = InertiaMatrixForCylinder(manipulator.m[i], manipulator.r[i], manipulator.h[i])
  inertia_matrices.append(inertia_matrix.get_inertia_matrix())

inertia_matrices

[array([[0.08395833, 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.000625  ]]),
 array([[0.08395833, 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.000625  ]]),
 array([[0.08395833, 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.000625  ]]),
 array([[0.08395833, 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.000625  ]]),
 array([[0.08395833, 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.000625  ]]),
 array([[0.08395833, 0.        , 0.        ],
        [0.        , 0.08395833, 0.        ],
        [0.        , 0.        , 0.000625  ]])]

In [27]:
# CHECK

# q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6')
# q_symb = [q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb]

# print(sp.diff(coms_matrices_symb[0][:3, 3], q_symb[0]))
# coms_matrices_symb[0][:3, 3]

### Calculate the Jacobian J_v

In [63]:
q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6')
q_symb = [q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb]


def calculate_jacobian_v(com_symb):
    jacobian_v = []

    for k in range(6):
        row = []
        for i in range(3):
            col = []
            for j in range(6):
                col.append(sp.diff(com_symb[k][i, 3], q_symb[j]))
            row.append(col)
        jacobian_v.append(row)

    return sp.Array(jacobian_v)


def calc_num_jacobian_v(com_symb, q_num):
    jac_v_symb = calculate_jacobian_v(com_symb)
    jac_v_num = jac_v_symb.subs({q1_symb: q_num[0], q2_symb: q_num[1], q3_symb: q_num[2], q4_symb: q_num[3], q5_symb: q_num[4], q6_symb: q_num[5]})
    return sp.Array(jac_v_num)

# Example of usage
q = [np.pi/2, -np.pi/3, np.pi/4, 0, np.pi/12, 0]
q_prev = [np.pi/2, -np.pi/4, np.pi/4, 0, np.pi/6, 0]

manipulator.set_config(q)
manipulator.set_prev_config(q_prev)

q_vals = manipulator.get_delta_q()
jac_v = calc_num_jacobian_v(coms_matrices_symb, q_vals)
jac_v

[[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], [[-0.482962913144534, -2.16489014058873e-17, 0, 0, 0, 0], [3.74969971630462e-17, 0.12940952255126, 0, 0, 0, 0], [0, 0.482962913144534, 0, 0, 0, 0]], [[-1.4488887394336, -6.4946704217662e-17, -2.16489014058873e-17, 0, 0, 0], [1.12490991489138e-16, 0.388228567653781, 0.12940952255126, 0, 0, 0], [0, 1.4488887394336, 0.482962913144534, 0, 0, 0]], [[-2.41481456572267, -1.08244507029437e-16, -6.4946704217662e-17, 0, 0, 0], [2.18101155793915e-16, 0.647047612756302, 0.388228567653781, 0, 0, 0], [0, 2.41481456572267, 1.4488887394336, 0, 0, 0]], [[-3.33079018075942, -1.41099704414105e-16, -9.78019016023301e-17, -0.12940952255126, -4.07792452632475e-17, 0], [3.35960836771689e-16, 1.02645713530756, 0.767638090205041, 2.11812383626407e-17, 0.25, 0], [0, 3.33079018075942, 2.36486435447036, 1.09362905948723e-17, 0.433012701892219, 0]], [[-4.19681558454386, -1.63512296371666e-16, -1.20214493559892e-16, -0.388228567653781, -1.22337735789743

### Calculate the Jacobian J_w

In [64]:
def calculate_jacobian_w(coms):
    jacobian_w = np.zeros((6, 3, 6))
    u = [np.array([0, 0, 1]),  coms[0][:3, 2],  coms[1][:3, 2], coms[2][:3, 2],  coms[3][:3, 2],  coms[4][:3, 2]]
    for i in range(6):
      for j in range(i+1):
        jacobian_w[i][:, j] = u[j]
    return jacobian_w

coms_matrices = calculate_com(manipulator)
jac_w = calculate_jacobian_w(coms_matrices)
jac_w

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  1.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  1.        ,  1.        ,  0.        ,
          0.        ,  0.        ],
        [ 1.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        , -0.96592583,
          0.        ,  0.        ],
        [ 0.        ,  1

### Define the rotation matrix

In [65]:
def define_R(com):
    R = np.zeros((6, 3, 3))
    com = np.array(com)
    for k in range(6):
        R[k] = com[k, :3, :3]
    return R

coms_matrices = calculate_com(manipulator)

R = define_R(coms_matrices)
R

array([[[-1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ],
        [ 0.        ,  1.        ,  0.        ]],

       [[-0.5       , -0.8660254 ,  0.        ],
        [ 0.        ,  0.        ,  1.        ],
        [-0.8660254 ,  0.5       ,  0.        ]],

       [[-0.25881905,  0.        , -0.96592583],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.96592583,  0.        , -0.25881905]],

       [[ 0.25881905, -0.96592583,  0.        ],
        [ 0.        ,  0.        ,  1.        ],
        [-0.96592583, -0.25881905,  0.        ]],

       [[ 0.        ,  0.        , -1.        ],
        [ 0.        , -1.        ,  0.        ],
        [-1.        ,  0.        ,  0.        ]],

       [[ 0.        ,  0.        , -1.        ],
        [ 0.        , -1.        ,  0.        ],
        [-1.        ,  0.        ,  0.        ]]])

In [66]:
jac_w = calculate_jacobian_w(coms_matrices)[0]
print(jac_w.shape)
jac_w_T = np.transpose(jac_w)
print("jac_w_T", jac_w_T)
print("R[0]", R[0])
print(jac_w_T @ R[0])

(3, 6)
jac_w_T [[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
R[0] [[-1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [84]:
from sys import flags
class MassMatrix:

    def __init__(self, manipulator):
        self.manipulator = manipulator
        self.com = calculate_com(self.manipulator)
        self.com_symb = calculate_com_symb(self.manipulator)

        if manipulator.get_prev_config() is not None\
         and manipulator.get_config() is not None:
          self.delta_q = manipulator.get_delta_q()
          self.numeric = True
          print("NB: Calculations are numeric.\n")

        else:
          self.numeric = False
          print("NB: Calculations are symbolic!\n")

    def compute_numeric(self):
      M = np.zeros((6, 6))
      # M = np.zeros((6, 6))
      for i in range(6):
        m_i = manipulator.m[i]
        inertia_matrx = InertiaMatrixForCylinder(m_i, manipulator.r[i],\
                                                 manipulator.h[i])
        I_i = inertia_matrix.get_inertia_matrix()
        R_i = define_R(self.com)[i]

        if self.numeric is False:
          Jv_i = calculate_jacobian_v(self.com_symb)[i]
        else:
          Jv_i = calc_num_jacobian_v(self.com_symb, self.delta_q)[i]

        Jw_i = calculate_jacobian_w(self.com)[i]
        # Jw_i = np.array([Jw_i])
        # ang = np.array([np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i])

        lin_part = m_i * np.transpose(Jv_i) @ Jv_i
        lin_part = lin_part.astype(float)  # Convert to float64
        ang_part = np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i

        M += lin_part + ang_part
        # print("ang", ang)
        # print("Jw_i^T @ R_i @ I_i @ R_i^T @ Jw_i", np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i)
        # M[i] += np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i
        # print(np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i).shape
        # @ I_i @ np.transpose(R_i) @ Jw_i

        #  (m_i * np.transpose(Jv_i) @ Jv_i) # + np.transpose(Jw_i) @ R_i @ I_i @ np.transpose(R_i) @ Jw_i)

      return M

mass_matrix = MassMatrix(manipulator)
M = mass_matrix.compute()
M
# validate_matrices([M])



NB: Calculations are numeric.



array([[3.73694531e+01, 2.76808289e-15, 1.96641174e-15, 1.99516962e+00,
        1.08279876e-15, 0.00000000e+00],
       [2.76808289e-15, 4.10942349e+01, 2.89117583e+01, 2.38389520e-16,
        8.46347162e+00, 0.00000000e+00],
       [1.96641174e-15, 2.89117583e+01, 2.09799066e+01, 1.82410085e-16,
        6.53161997e+00, 0.00000000e+00],
       [1.99516962e+00, 2.38389520e-16, 1.82410085e-16, 2.63841128e-01,
        1.08721426e-16, 6.03703641e-04],
       [1.08279876e-15, 8.46347162e+00, 6.53161997e+00, 1.08721426e-16,
        2.66791667e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.03703641e-04,
        0.00000000e+00, 6.25000000e-04]])

In [88]:
# Print the matrix in a more friendly way
def validate_mass_matrix(matrix):
    for row in matrix:
        formatted_row = ["{:.6f}".format(entry) for entry in row]
        print(formatted_row)

validate_mass_matrix(M)

['37.369453', '0.000000', '0.000000', '1.995170', '0.000000', '0.000000']
['0.000000', '41.094235', '28.911758', '0.000000', '8.463472', '0.000000']
['0.000000', '28.911758', '20.979907', '0.000000', '6.531620', '0.000000']
['1.995170', '0.000000', '0.000000', '0.263841', '0.000000', '0.000604']
['0.000000', '8.463472', '6.531620', '0.000000', '2.667917', '0.000000']
['0.000000', '0.000000', '0.000000', '0.000604', '0.000000', '0.000625']


# Coriolis matrix

In [92]:
q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6')
q_symb = [q1_symb, q2_symb, q3_symb, q4_symb, q5_symb, q6_symb]


class CoriolisMatrix:
  def __init__(self, mass_matrix):
    self.mass_matrix = mass_matrix


  def compute(self):
    M = self.mass_matrix
    coriolis_matrix =  np.zeros((6, 6))
    for i in range(6):
      for j in range(6):
        for k in range(6):
          print(M[i, j])
          coriolis_matrix[i, j] += 1/2 * (sp.diff(M[i, j], q_symb[k]) + sp.diff(M[i, k], q_symb[j]) - sp.diff(M[j, k], q_symb[i]))

    return coriolis_matrix

C = CoriolisMatrix(M)
C.compute()

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [93]:
M

array([[3.73694531e+01, 2.76808289e-15, 1.96641174e-15, 1.99516962e+00,
        1.08279876e-15, 0.00000000e+00],
       [2.76808289e-15, 4.10942349e+01, 2.89117583e+01, 2.38389520e-16,
        8.46347162e+00, 0.00000000e+00],
       [1.96641174e-15, 2.89117583e+01, 2.09799066e+01, 1.82410085e-16,
        6.53161997e+00, 0.00000000e+00],
       [1.99516962e+00, 2.38389520e-16, 1.82410085e-16, 2.63841128e-01,
        1.08721426e-16, 6.03703641e-04],
       [1.08279876e-15, 8.46347162e+00, 6.53161997e+00, 1.08721426e-16,
        2.66791667e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.03703641e-04,
        0.00000000e+00, 6.25000000e-04]])