<a href="https://colab.research.google.com/github/illusoryTwin/FoR/blob/main/assig1/FundamentalsOfRobotics_Assig1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1. Forward Kinematics
##  Antropomorphic elbow with a spherical wrist

## Elbow
![Image](https://drive.google.com/uc?export=view&id=17zG41RTwz8amP0VphfeS9KIdjZVnPH_0)


## Spherical wrist
![Image](https://drive.google.com/uc?export=view&id=1NzAcCwKtdXwueeBZS20bo7Jra0075qQn)


## Manipulator
![Image](https://drive.google.com/uc?export=view&id=1YTnHb9JNJHb5IChMIZxDhtwBxIIelD-w)


# Transformation matrices

The  rotation matrices are defined as follows:

$$R_x(\theta)=
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & \cos(\theta) & -\sin(\theta) & 0 \\
    0 & \sin(\theta) & \cos(\theta) & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}$$

$$R_y(\theta)=
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & \cos(\theta) & -\sin(\theta) & 0 \\
    0 & \sin(\theta) & \cos(\theta) & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}$$

$$R_z(\theta)=
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & \cos(\theta) & -\sin(\theta) & 0 \\
    0 & \sin(\theta) & \cos(\theta) & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}$$

The translation matrices are defined as follows:

$$T_x(dx)=
\begin{bmatrix}
    1 & 0 & 0 & dx \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}$$

$$T_y(dy)=
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & dy \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}$$

$$T_z(dz)=
\begin{bmatrix}
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & dz \\
    0 & 0 & 0 & 1 \\
\end{bmatrix}$$

In [1]:
import numpy as np
import sympy as sp

def rotate_x(theta):
    cos_theta = sp.cos(theta)
    sin_theta = sp.sin(theta)
    rot_matrix_x = sp.Matrix([[1, 0, 0, 0],
                              [0, cos_theta, -sin_theta, 0],
                              [0, sin_theta, cos_theta, 0],
                              [0, 0, 0, 1]])
    return rot_matrix_x

def rotate_y(theta):
    cos_theta = sp.cos(theta)
    sin_theta = sp.sin(theta)
    rot_matrix_y = sp.Matrix([[cos_theta, 0, sin_theta, 0],
                              [0, 1, 0, 0],
                              [-sin_theta, 0, cos_theta, 0],
                              [0, 0, 0, 1]])
    return rot_matrix_y

def rotate_z(theta):
    cos_theta = sp.cos(theta)
    sin_theta = sp.sin(theta)
    rot_matrix_z = sp.Matrix([[cos_theta, -sin_theta, 0, 0],
                              [sin_theta, cos_theta, 0, 0],
                              [0, 0, 1, 0],
                              [0, 0, 0, 1]])
    return rot_matrix_z

def translate_x(dx):
    translation_matrix_x = sp.Matrix([[1, 0, 0, dx],
                                      [0, 1, 0, 0],
                                      [0, 0, 1, 0],
                                      [0, 0, 0, 1]])
    return translation_matrix_x

def translate_y(dy):
    translation_matrix_y = sp.Matrix([[1, 0, 0, 0],
                                      [0, 1, 0, dy],
                                      [0, 0, 1, 0],
                                      [0, 0, 0, 1]])
    return translation_matrix_y

def translate_z(dz):
    translation_matrix_z = sp.Matrix([[1, 0, 0, 0],
                                      [0, 1, 0, 0],
                                      [0, 0, 1, dz],
                                      [0, 0, 0, 1]])
    return translation_matrix_z


# Forward Kinematics

There are two approaches for solving forward kinematics problem:

## (1)
For this manipulator, consisting of an anthropomorphic arm with a spherical wrist,
the direct kinematics problem cannot be obtained by pure multiplication of transformation matrices ${}^0T_3$ and ${}^3T_6$ since
the elbow needs to coincide with the spherical wrist.
We need to transform from the final reference frame of the elbow to the base reference frame of the wrist.
So, one more transformation matrix has to be introduced, this matrix will describe transition between those two reference frames.

## (2)
We multiply all the transformation matrices - transitions between the reference frames.


## Let's solve the problem via Method 2

In [ ]:
import sympy as sp
theta1, theta2, theta3, theta4, theta5, theta6, l1, l2, l3, l4, l5, l6, pi = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6 l1 l2 l3 l4 l5 l6 pi')


T_01 = rotate_z(theta1) * translate_z(l1) * rotate_z(sp.pi/2) * rotate_x(sp.pi/2)
T_12 = rotate_z(theta2) * translate_x(l2)
T_23 = rotate_z(theta3) * translate_x(l3) * rotate_y(sp.pi/2) * rotate_z(sp.pi/2)

T_34 = rotate_z(theta4) * translate_z(l4) * rotate_x(-sp.pi/2) * rotate_z(-sp.pi)
T_45 = rotate_z(theta5) * translate_y(l5) * rotate_x(-sp.pi/2)
T_56 = rotate_z(theta6) * translate_z(l6)


T1 = T_01*T_12*T_23*T_34*T_45*T_56
T1

Matrix([
[   ((-(sin(theta1)*sin(theta2)*cos(theta3) + sin(theta1)*sin(theta3)*cos(theta2))*cos(theta4) - sin(theta4)*cos(theta1))*cos(theta5) + (sin(theta1)*sin(theta2)*sin(theta3) - sin(theta1)*cos(theta2)*cos(theta3))*sin(theta5))*cos(theta6) + ((sin(theta1)*sin(theta2)*cos(theta3) + sin(theta1)*sin(theta3)*cos(theta2))*sin(theta4) - cos(theta1)*cos(theta4))*sin(theta6),    -((-(sin(theta1)*sin(theta2)*cos(theta3) + sin(theta1)*sin(theta3)*cos(theta2))*cos(theta4) - sin(theta4)*cos(theta1))*cos(theta5) + (sin(theta1)*sin(theta2)*sin(theta3) - sin(theta1)*cos(theta2)*cos(theta3))*sin(theta5))*sin(theta6) + ((sin(theta1)*sin(theta2)*cos(theta3) + sin(theta1)*sin(theta3)*cos(theta2))*sin(theta4) - cos(theta1)*cos(theta4))*cos(theta6),   -(-(sin(theta1)*sin(theta2)*cos(theta3) + sin(theta1)*sin(theta3)*cos(theta2))*cos(theta4) - sin(theta4)*cos(theta1))*sin(theta5) + (sin(theta1)*sin(theta2)*sin(theta3) - sin(theta1)*cos(theta2)*cos(theta3))*cos(theta5),     -l2*sin(theta1)*cos(theta2) 

In [ ]:
import sympy as sp

theta1, theta2, theta3, theta4, theta5, theta6, l1, l2, l3, l4, l5, l6 = sp.symbols('theta1 theta2 theta3 theta4 theta5 theta6 l1 l2 l3 l4 l5 l6')


T_01 = rotate_z(theta1) * translate_z(l1) * rotate_z(pi/2) * rotate_x(pi/2)
T_12 = rotate_z(theta2) * translate_x(l2)
T_23 = rotate_z(theta3) * translate_x(l3) * rotate_y(pi/2) * rotate_z(pi/2)

T_01*T_12*T_23

Matrix([
[ sin(theta1)*sin(theta2)*cos(theta3) + sin(theta1)*sin(theta3)*cos(theta2), cos(theta1),  sin(theta1)*sin(theta2)*sin(theta3) - sin(theta1)*cos(theta2)*cos(theta3), -l2*sin(theta1)*cos(theta2) + l3*sin(theta1)*sin(theta2)*sin(theta3) - l3*sin(theta1)*cos(theta2)*cos(theta3)],
[-sin(theta2)*cos(theta1)*cos(theta3) - sin(theta3)*cos(theta1)*cos(theta2), sin(theta1), -sin(theta2)*sin(theta3)*cos(theta1) + cos(theta1)*cos(theta2)*cos(theta3),  l2*cos(theta1)*cos(theta2) - l3*sin(theta2)*sin(theta3)*cos(theta1) + l3*cos(theta1)*cos(theta2)*cos(theta3)],
[                        -sin(theta2)*sin(theta3) + cos(theta2)*cos(theta3),           0,                          sin(theta2)*cos(theta3) + sin(theta3)*cos(theta2),                                 l1 + l2*sin(theta2) + l3*sin(theta2)*cos(theta3) + l3*sin(theta3)*cos(theta2)],
[                                                                         0,           0,                                                                    

# **Numeric forward kinematics for different configurations**

In [ ]:
import numpy as np

def rotate_x(theta):
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    rot_matrix_x = np.array([[1, 0, 0, 0],
                             [0, cos_theta, -sin_theta, 0],
                             [0, sin_theta, cos_theta, 0],
                             [0, 0, 0, 1]])
    return rot_matrix_x

def rotate_y(theta):
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    rot_matrix_y = np.array([[cos_theta, 0, sin_theta, 0],
                              [0, 1, 0, 0],
                              [-sin_theta, 0, cos_theta, 0],
                              [0, 0, 0, 1]])
    return rot_matrix_y

def rotate_z(theta):
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    rot_matrix_z = np.array([[cos_theta, -sin_theta, 0, 0],
                              [sin_theta, cos_theta, 0, 0],
                              [0, 0, 1, 0],
                              [0, 0, 0, 1]])
    return rot_matrix_z

def translate_x(dx):
    translation_matrix_x = np.array([[1, 0, 0, dx],
                                     [0, 1, 0, 0],
                                     [0, 0, 1, 0],
                                     [0, 0, 0, 1]])
    return translation_matrix_x

def translate_y(dy):
    translation_matrix_y = np.array([[1, 0, 0, 0],
                                     [0, 1, 0, dy],
                                     [0, 0, 1, 0],
                                     [0, 0, 0, 1]])
    return translation_matrix_y

def translate_z(dz):
    translation_matrix_z = np.array([[1, 0, 0, 0],
                                     [0, 1, 0, 0],
                                     [0, 0, 1, dz],
                                     [0, 0, 0, 1]])
    return translation_matrix_z

In [ ]:
# Define a function to make the values of the matrix to be within the tolerance

def validate_matrix(matrix):

    tolerance = 1e-12
    def is_close_to_zero(value):
        return abs(value) < tolerance

    # Iterate through each element in the matrix
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            # If the element is close to zero, set it to zero
            if is_close_to_zero(matrix[i][j]):
                matrix[i][j] = 0

l1 = 0.3
l2 = 1
l3 = 0.3
l4 = 0.5
l5 = 0.3
l6 = 0.4

def forward_kinematics(q):

    theta1, theta2, theta3, theta4, theta5, theta6 = q

    T_0 = np.identity(4)
    T_01 = rotate_z(theta1) @ translate_z(l1) @ rotate_z(np.pi/2) @ rotate_x(np.pi/2)
    T_12 = rotate_z(theta2) @ translate_x(l2)
    T_23 = rotate_z(theta3) @ translate_x(l3) @ rotate_y(np.pi/2) @ rotate_z(np.pi/2)

    T_34 = rotate_z(theta4) @ translate_z(l4) @ rotate_x(-np.pi/2) @ rotate_z(-np.pi)
    T_45 = rotate_z(theta5) @ translate_y(l5) @ rotate_x(-np.pi/2)
    T_56 = rotate_z(theta6) @ translate_z(l6)


    f_k_transform = T_0 @ T_01 @ T_12 @ T_23 @ T_34 @ T_45 @ T_56
    validate_matrix(f_k_transform)
    return f_k_transform

In [ ]:
config1 = [np.pi/2, 0, 0, 0, np.pi/3, 0]
config2 = [-np.pi/3, 0, np.pi/3, np.pi/6, -np.pi/12, 0]
configs = [config1, config2]

for config in configs:
  sol = forward_kinematics(config)
  print("Forward kinematics solution:\n", sol)

Forward kinematics solution:
 [[-0.8660254   0.         -0.5        -2.15      ]
 [ 0.         -1.          0.          0.        ]
 [-0.5         0.          0.8660254   0.90621778]
 [ 0.          0.          0.          1.        ]]
Forward kinematics solution:
 [[ 0.27383384 -0.8080127   0.52166129  1.57759847]
 [ 0.71577558  0.53349365  0.45061053  1.01542737]
 [-0.64240202  0.25        0.72444437  1.49993138]
 [ 0.          0.          0.          1.        ]]
